### ISSUE TITLE
Update Bios

### ISSUE THREAD

**Issue by firasm** [open-resources/stats_bank#1]
Please add new bios to the `about/bios.md` page

**Comment by firasm** [comment]
Hi @SamuelStreet just a reminder to do this asap!

**Comment by SamuelStreet** [comment]
> Hi @SamuelStreet just a reminder to do this asap!

It should now be updated, I updated it last night and then I fixed something this morning. Does it show the updates I made on your computer? I only wonder because it says there was some sort of error, but it also says that it merged and I see all the changes on the https://github.com/open-resources/stats_bank/blob/main/about/bio.md

**Comment by firasm** [comment]
Thanks - this is done now !
